---
# =================================================
# Install Node Exporter
# =================================================
- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ NODE_EXPORTER_VERSION }}/node_exporter-{{ NODE_EXPORTER_VERSION }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

# =================================================
# Extract Tarball
# =================================================
- name: Extract Node Exporter tarball
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/opt"
    remote_src: yes

# =================================================
# Check
# =================================================
- name: Check if /opt/node_exporter exists
  stat:
    path: /opt/node_exporter
  register: node_exporter_dir

# =================================================
# Rename Folder
# =================================================
- name: Rename Node Exporter directory
  command: mv /opt/node_exporter-{{ NODE_EXPORTER_VERSION }}.linux-amd64 /opt/node_exporter
  when: not node_exporter_dir.stat.exists

# =================================================
# Create Node Exporter SystemD Service File
# =================================================
- name: Create a Node Exporter systemd service file
  copy:
    dest: "/etc/systemd/system/node_exporter.service"
    content: |
      [Unit]
      Description=Node Exporter
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=nobody
      Group=nogroup
      Type=simple
      ExecStart=/opt/node_exporter/node_exporter

      [Install]
      WantedBy=multi-user.target

  notify:
    - restart_node_exporter
